### ISSUE TITLE
generated_on was removed but is still referenced in details view

### ISSUE THREAD

**Issue by marksavoca** [fguillen/simplecov-rcov#34]
generated_on was removed from being set but is still referenced in details view causing an ERB error.

 <p>Generated on <%= generated_on %> with

**Comment by joshRpowell** [comment]
https://github.com/search?q=repo%3Afguillen%2Fsimplecov-rcov%20generated_on&type=code

**Comment by ildomar-grings** [comment]
Some stack trace that may help you guys:
```
(erb):69:in `format': undefined local variable or method `generated_on' for #<SimpleCov::Formatter::RcovFormatter:0x000000010991cc10 @asset_output_path=
(...)
	from /~home/.rbenv/versions/3.2.2/lib/ruby/3.2.0/erb.rb:429:in `eval'
	from /~home/.rbenv/versions/3.2.2/lib/ruby/3.2.0/erb.rb:429:in `result'
	from /~home/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/simplecov-rcov-0.3.5/lib/simplecov-rcov.rb:47:in `write_file'
	from /~home/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/simplecov-rcov-0.3.5/lib/simplecov-rcov.rb:34:in `format'
	from /~home/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/simplecov-0.22.0/lib/simplecov/result.rb:51:in `format!'
	from /~home/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/simplecov-0.22.0/lib/simplecov/configuration.rb:197:in `block in at_exit'
	from /~home/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/simplecov-0.22.0/lib/simplecov.rb:189:in `run_exit_tasks!'
	from /~home/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/simplecov-0.22.0/lib/simplecov.rb:179:in `at_exit_behavior'
	from /~home/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/simplecov-0.22.0/lib/simplecov/defaults.rb:30:in `block in <top (required)>'
```

**Comment by brucebolt** [comment]
I've raised a PR to fix this: https://github.com/fguillen/simplecov-rcov/pull/35
